# Generated by Django 2.2.4 on 2021-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoompost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmodel',
            name='event',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
