# Generated by Django 2.2.4 on 2021-04-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoompost', '0002_guestmodel_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guestmodel',
            old_name='event',
            new_name='event_date',
        ),
        migrations.RemoveField(
            model_name='guestmodel',
            name='user',
        ),
    ]
